config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get     '/about',         to: 'static_pages#about'
  get     '/contact',       to: 'static_pages#contact'
  
  get     '/signup',        to: 'users#new'
  post    '/signup',        to: 'users#create'

  get     '/login',         to: 'sessions#new'
  post    '/login',         to: 'sessions#create'
  delete  '/logout',        to: 'sessions#destroy'

  post    '/attend',        to: 'attendances#create'
  get     '/attend',        to: 'attendances#create'
  delete  '/unattend',      to: 'attendances#destroy'

  get     '/invite',        to: 'invitations#new'
  post    '/invite',        to: 'invitations#create'
  get     '/notifications', to: 'invitations#show'
  get     '/invitation',    to: 'invitations#destroy'

  resources :users
  resources :events
end

app/models/user.rb
class User < ApplicationRecord
  has_many :hosted_events, class_name: 'Event', foreign_key: 'creator_id'

  has_many :attendances
  has_many :attended_events, through: :attendances, source: :event

  has_many :sent_invitations, class_name: 'Invitation', foreign_key: 'inviter_id'
  has_many :received_invitations, class_name: 'Invitation', foreign_key: 'invited_id'
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6, maximum: 140 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "You have signed up."
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Your information has been updated."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "This user has been deleted."
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      unless @user == current_user
        flash[:danger] = "You are not authorized."
        redirect_to root_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.html.erb
<div class="alert-warning">
	<% if @user.errors.any? %>
		<ul>
			<h5>This form contains <%= pluralize(@user.errors.count, "error") %>:</h5>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<%= render 'errors' %>
	<div class="form-group">
		<h4><%= f.label :email %></h4>
		<%= f.text_field :email, class: "form-control" %>
	</div>
	<div class="form-group">
		<h4><%= f.label :password %></h4>
		<%= f.password_field :password, class: "form-control" %>
	</div>
	<div class="form-group">
		<h4><%= f.label :password_confirmation %></h4>
		<%= f.password_field :password_confirmation, class: "form-control" %>
	</div>
	<%= f.submit yield(:button_text), class: "btn-primary btn-lg" %>
<% end %>

app/views/users/_user.html.erb
<li class="list-group-item"><%= link_to user.email, user %></li>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:button_text, "Submit Changes") %>

<h1>Update Information</h1>

<hr>

<%= render 'form' %>

app/views/users/index.html.erb
<% provide(:title, "Users") %>


<h1>Users</h1>

<hr>

<ul class="list-group">
	<%= render @users %>
</ul>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<% provide(:button_text, "Sign Up") %>

<h1>Sign Up</h1>

<hr>

<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, "Profile") %>

<h1>Profile</h1>

<% if current_user != @user %>
	<%= link_to "Invite", invite_path(user_id: @user.id), class: "btn-primary btn-lg" %>
<% end %>

<hr>

<p>This is the account of <%= @user.email %>.</p>

<%= link_to "Edit Account", edit_user_path(@user) %>
<br>
<%= link_to "Delete Account", @user, method: :delete, data: { confirm: "Are you sure?" } %>

<hr>

<h2>Hosted Events</h2>

<%= render @user.hosted_events %>

<hr>

<h2>Attending Events</h2>

<%= render @user.attended_events.future_events %>

<hr>

<h2>Attended Events</h2>

<%= render @user.attended_events.past_events %>