config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get     '/about',         to: 'static_pages#about'
  get     '/contact',       to: 'static_pages#contact'
  
  get     '/signup',        to: 'users#new'
  post    '/signup',        to: 'users#create'

  get     '/login',         to: 'sessions#new'
  post    '/login',         to: 'sessions#create'
  delete  '/logout',        to: 'sessions#destroy'

  post    '/attend',        to: 'attendances#create'
  get     '/attend',        to: 'attendances#create'
  delete  '/unattend',      to: 'attendances#destroy'

  get     '/invite',        to: 'invitations#new'
  post    '/invite',        to: 'invitations#create'
  get     '/notifications', to: 'invitations#show'
  get     '/invitation',    to: 'invitations#destroy'

  resources :users
  resources :events
end

app/models/event.rb
class Event < ApplicationRecord
  default_scope { order(start_time: :asc) }
  scope :past_events, -> { where('start_time < ?', DateTime.current) }
  scope :future_events, -> { where('start_time > ?', DateTime.current) }

  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'

  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances, source: :user

  has_many :invitations, dependent: :destroy

  validates :title, presence: true, length: { minimum: 6, maximum: 140 }
  validates :description, presence: true, length: { minimum: 40, maximum: 1500 }
  validates :start_time, presence: true
  validates :location, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @future_events = Event.future_events
    @past_events = Event.past_events
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = current_user.hosted_events.new
  end

  def create
    @event = current_user.hosted_events.new(event_params)
    if @event.save
      flash[:success] = "Your event has been created."
      redirect_to @event
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Your event has been updated."
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:success] = "Event has been cancelled."
    redirect_to root_path
  end

  private

    def event_params
      params.require(:event).permit(:title, :location, :start_time, :description)
    end

    def logged_in_user
      unless logged_in?
        flash[:info] = "You must be logged in to do that."
        redirect_to login_path
      end
    end

    def correct_user
      @user = Event.find(params[:id]).creator
      unless @user == current_user
        flash[:danger] = "You are not authorized."
        redirect_to root_path
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_errors.html.erb
<div class="alert-warning">
	<% if @event.errors.any? %>
		<ul>
			<h5>This form contains <%= pluralize(@event.errors.count, "error") %>:</h5>
			<% @event.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>
</div>

app/views/events/_event.html.erb
<li class="list-group-item">
	<%= link_to event.title, event %>
	<br>
	<%= event.start_time.strftime("%D - %I:%M %p") %>
</li>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
	<%= render 'errors' %>
	<div class="form-group">
		<h4><%= f.label :title %></h4>
		<%= f.text_field :title, class: "form-control" %>
	</div>
	<div class="form-group">
		<h4><%= f.label :location %></h4>
		<%= f.text_field :location, class: "form-control" %>
	</div>
	<div class="form-group">
		<h4><%= f.label :start_time %></h4>
		<%= f.datetime_select :start_time, start_year: Time.current.year, ampm: true %>
	</div>
	<div class="form-group">
		<h4><%= f.label :description %></h4>
		<%= f.text_area :description, size: "30x10", class: "form-control" %>
	</div>
	<%= f.submit yield(:button), class: "btn-primary btn-lg" %>
<% end %>
<br>
<%= link_to "Cancel", root_path %>

app/views/events/edit.html.erb
<% provide(:title, "Edit Event") %>
<% provide(:button, "Submit Changes") %>

<h1>Edit <%= @event.title %></h1>

<hr>

<%= render 'form' %>

app/views/events/index.html.erb
<% provide(:title, "Events") %>

<h1>Events</h1>

<hr>

<h2>Upcoming</h2>

<ul class="list-group">
	<%= render @future_events %>
</ul>

<hr>

<h2>Past</h2>

<ul class="list-group">
	<%= render @past_events %>
</ul>

app/views/events/new.html.erb
<% provide(:title, "New Event") %>
<% provide(:button, "Create Event") %>

<h1>New Event</h1>

<hr>

<%= render 'form' %>

app/views/events/show.html.erb
<% provide(:title, @event.title) %>

<h1><%= @event.title %></h1>

<p>Created by <%= @event.creator.email %></p>

<% if logged_in? %>
	<% if @event.attendees.include?(current_user) %>
		<%= link_to "Leave", unattend_path(event_id: @event.id, user_id: current_user.id), method: :delete, class: "btn-primary btn-lg" %>
	<% else %>
		<%= link_to "Attend", attend_path(event_id: @event.id, user_id: current_user.id), method: :post, class: "btn-primary btn-lg" %>
	<% end %>
<% end %>

<hr>

<p>Time: <%= @event.start_time.strftime("%I:%M %p, %D") %></p>

<p>Location: <%= @event.location %></p>

<hr>

<p><%= @event.description %></p>

<hr>

<%= link_to "Edit Event", edit_event_path %>
<br>
<%= link_to "Delete Event", @event, method: :delete, data: { confirm: "Are you sure you want to delete this event? It can not be recovered." } %>

<hr>

<h2>Attending</h2>

<% @event.attendees.each do |attendee| %>
	<li class="list-group-item">
		<%= link_to attendee.email, attendee %>
		<% if current_user == @event.creator %>
			<br>
			<%= link_to "Remove", unattend_path(event_id: @event.id, user_id: attendee.id), method: :delete, class: "btn-seconday btn-sm" %>
		<% end %>
	</li>
<% end %>