config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get     '/about',         to: 'static_pages#about'
  get     '/contact',       to: 'static_pages#contact'
  
  get     '/signup',        to: 'users#new'
  post    '/signup',        to: 'users#create'

  get     '/login',         to: 'sessions#new'
  post    '/login',         to: 'sessions#create'
  delete  '/logout',        to: 'sessions#destroy'

  post    '/attend',        to: 'attendances#create'
  get     '/attend',        to: 'attendances#create'
  delete  '/unattend',      to: 'attendances#destroy'

  get     '/invite',        to: 'invitations#new'
  post    '/invite',        to: 'invitations#create'
  get     '/notifications', to: 'invitations#show'
  get     '/invitation',    to: 'invitations#destroy'

  resources :users
  resources :events
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :event
  belongs_to :inviter, class_name: 'User', foreign_key: 'inviter_id'
  belongs_to :invited, class_name: 'User', foreign_key: 'invited_id'

  validates :event, uniqueness: { scope: [:inviter, :invited] }
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :logged_in_user
  before_action :different_user, only: :new

  def show
    invitations = current_user.received_invitations
    @events = []
    invitations.each do |invitation|
      @events << Event.find(invitation.event_id)
    end
  end

  def new
    @invitation = current_user.sent_invitations.new
    @user = User.find(params[:user_id])
    @invitation.invited = @user

    @possible_events = [] # move logic to Model?
    current_user.hosted_events.each do |event|
      unless @user.attended_events.include?(event)
        @possible_events << event
      end
    end
  end

  def create
    @invitation = Invitation.new(invitation_params)
    @user = User.find(params[:invitation][:invited_id])
    if @invitation.save
      flash[:success] = "Your invitation has been sent."
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    @invitation = Invitation.find_by(invited_id: current_user.id, event_id: params[:event_id])
    @invitation.destroy
    if params[:accept] == 'true'
      redirect_to attend_path(event_id: params[:event_id], user_id: current_user.id)
    else
      redirect_to notifications_path
    end
  end

  private

    def invitation_params
      params.require(:invitation).permit(:invited_id, :inviter_id, :event_id)
    end

    def logged_in_user
      unless logged_in?
        flash[:info] = "You must be logged in to do that."
        redirect_to login_path
      end
    end

    def different_user
      user = User.find(params[:user_id])
      if current_user == user
        flash[:info] = "You can't invite yourself to events!"
        redirect_to root_path
      end
    end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/new.html.erb
<% provide(:title, "Invite") %>

<h1>Invite</h1>

<hr>

<p>Hello, <%= current_user.email %></p>

<p>It looks like you want to invite <%= @user.email %> to one of your events!</p>

<p>Which event would you like them to attend?</p>

<%= form_for(@invitation, url: invite_path) do |f| %>
	<% if @invitation.errors.any? %>
		<div class="alert-warning">
			<ul>
				<h5>This form contains <%= pluralize(@invitation.errors.count, "error") %>:</h5>
				<% @invitation.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.hidden_field :invited_id, value: @invitation.invited_id %>
	<%= f.hidden_field :inviter_id, value: @invitation.inviter_id %>
	<%= f.collection_select :event_id, @possible_events, :id, :title %>
	<br>
	<%= f.submit "Invite", class: "btn-primary btn-lg" %>
<% end %>

app/views/invitations/show.html.erb
<% provide(:title, "Notifications") %>

<h1>Notifications</h1>

<hr>

<ul class="list-group">
	<% @events.each do |event| %>
		<li class="list-group-item">
			<%= event.title %>
			<br>
			<%= event.start_time.strftime("%D - %I:%M %p") %>
			<br>
			<%= link_to "Accept Invitation", invitation_path(accept: true, event_id: event.id) %>
			<br>
			<%= link_to "Reject Invitation", invitation_path(accept: false, event_id: event.id) %>
		</li>
	<% end %>
</ul>