config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get     '/about',         to: 'static_pages#about'
  get     '/contact',       to: 'static_pages#contact'
  
  get     '/signup',        to: 'users#new'
  post    '/signup',        to: 'users#create'

  get     '/login',         to: 'sessions#new'
  post    '/login',         to: 'sessions#create'
  delete  '/logout',        to: 'sessions#destroy'

  post    '/attend',        to: 'attendances#create'
  get     '/attend',        to: 'attendances#create'
  delete  '/unattend',      to: 'attendances#destroy'

  get     '/invite',        to: 'invitations#new'
  post    '/invite',        to: 'invitations#create'
  get     '/notifications', to: 'invitations#show'
  get     '/invitation',    to: 'invitations#destroy'

  resources :users
  resources :events
end

app/views/layouts/_footer.html.erb
<footer class="navbar fixed-bottom navbar-light">
	<ul class="nav">
		<li class="nav-item">
			<%= link_to "Home", root_path, class: "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to "About", about_path, class: "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to "Contact", contact_path, class: "nav-link" %>
		</li>
	</ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-light">
	<%= link_to "Event.io", root_path, class: "navbar-brand" %>
	<ul class="nav">
		<li class="nav-item">
			<%= link_to "New", new_event_path, class: "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to "Events", events_path, class: "nav-link" %>
		</li>
		<li class="nav-item">
			<%= link_to "Users", users_path, class: "nav-link" %>
		</li>
		<% if !logged_in? %>
			<li class="nav-item">
				<%= link_to "Sign Up", signup_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
				<%= link_to "Log In", login_path, class: "nav-link" %>
			</li>
		<% else %>
			<li class="nav-item">
				<%= link_to "Account", current_user, class: "nav-link" %>
			</li>
			<li class="nav-item">
				<% notifications = current_user.received_invitations.count %>
				<%= link_to "Notifications #{notifications == 0 ? "" : "(#{notifications})"}", notifications_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
				<%= link_to "Log Out", logout_path, method: :delete, class: "nav-link" %>
			</li>
		<% end %>
	</ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  	<meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= full_title(yield(:title)) %></title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>

    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>

  	<div class="center">
    	<%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>